"""Migração Inicial

Revision ID: b350511e8309
Revises: 
Create Date: 2022-08-07 10:59:41.483176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b350511e8309'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATETIME(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receitas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('valor', sa.FLOAT(), nullable=False),
    sa.Column('data', sa.DATETIME(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receitas')
    op.drop_table('despesas')
    # ### end Alembic commands ###
